### ISSUE TITLE
Support for SSL enabled servers.

### ISSUE THREAD

**Issue by JakkinStewart** [Taiiwo/IRCLinkBot#9]
Are you planning on supporting SSL in your IRC bot?
If so, please let me know. I've been working a little on your code to attempt to extend your bot to SSL servers.

**Comment by Taiiwo** [comment]
Great! If you have a completed solution, make a pull request. If you need
some help, or want to ask some questions, just make another issue or ask in
this one. Thanks :)

**Comment by Taiiwo** [comment]
support added
